### ISSUE TITLE
Rotate then crop

### ISSUE THREAD

**Issue by theevilqueen77** [viliusle/miniPaint#110]
Been banging my head against the wall for this issue for a little while now without any solutions. It cuts off the top and bottom part of the selection when I crop. When I went to check it out on the demo you have set up it actually completely wiped the image. Unsure what is going on with your code (I realize you wouldn't really be able to help with mine since I've done a lot of custom work to it).

**Comment by viliusle** [comment]
You must understand how rotate works. Default rotate alone is not good, because it rotates not from center, but from 0,0 coordinates. So normal rotate (by center) is done using translate and default rotate. Result is nice, but if you want to do additional action to rotated layer, you have to remember that it is "transformed", "translated"

Of course, after rotation, rotated layer can be saved directly, so we will not need to touch these transformations again. But we would loose image quality here, if we do more that 1 rotation.
Current rotation is done from original source every time it need to be rendered. So we have max quality.

In app, rotation is done here:
https://github.com/viliusle/miniPaint/blob/master/src/js/core/base-layers.js#L254

Hope it helps.

p.s. i still want to find perfect solution here too.

**Comment by viliusle** [comment]
>I realize you wouldn't really be able to help with mine since I've done a lot of custom work to it

This is more like core problem, and i believe you did not modifed core too much. If yes - let me know why, maybe it can be fixed from my side as well.

So i beleive our codes have same problems.

**Comment by theevilqueen77** [comment]
Maybe I am missing something, but what was the big change from version 3 to 4? This rotate and crop issue doesn't occur there.

**Comment by theevilqueen77** [comment]
Okay, wasn't sure if there was a short fix that I could implement where I could stuff old code from version 3 into the newest version until I could figure out a more acceptable solution. Thanks for the response. If I figure something out I'll make sure to pass it along to you.

**Comment by theevilqueen77** [comment]
@viliusle I just wanted to let you know that I was able to get it to work with a little bit of maneuvering. When I went to crop, I checked whether the image was rotated 90 or 270 degrees (we took out the custom angle for our uses). If it was we rotate the image back to 0 and then adjusted the selection coordinates appropriately. After that we rotated the image back to original angle of 90 or 270. Hope this helps!
