### ISSUE TITLE
Slightly improve mobile support

### ISSUE THREAD

**Issue by chiaravalle** [viliusle/miniPaint#167]
Hello there.
I like this App so much, and it works on my mobile so well.
The only drawback is that, when content overflows (eg. menu or window content), there's no ability to scroll down to see it.

Keep up the great work!

**Comment by viliusle** [comment]
I am not sure if i understand problem, but this should help:

![2222](https://user-images.githubusercontent.com/3708786/94370739-543c6400-00fa-11eb-9bf9-7298c2df8f8f.png)

**Comment by chiaravalle** [comment]
No, I'm talking about the UI

**Comment by viliusle** [comment]
I stilll do not understand your issue.

**Comment by Giwayume** [comment]
Do you mind if I do a UI overhaul & try to make it a little more intuitive or are you attached to the way it works right now?

**Comment by Giwayume** [comment]
In terms of this issue, when the application window is height-limited, many parts of the UI don't account for this. For example, the effects dropdown is very tall and can easily get cut off on small screens so you can't click on the bottom options in the dropdown.

**Comment by viliusle** [comment]
I looked again, tested and i see and understand these issues:

- Menu does not fit on screens with small height screens (for example effects) 
- Left side tools does not fit on small height screens - normal priority
- top tools (on right side after logo) does not fit on narrow screen
- mobile button is useless on mobile, because right side tools (except preview section) does not fit anyway  ?
- modal windows (for example save) can be improved on small screens, also can not be closed !!!

p.s. i will try to edit this list, so if anything is missed - please add it in comments.

**Comment by viliusle** [comment]
>Do you mind if I do a UI overhaul & try to make it a little more intuitive or are you attached to the way it works right now?

I am really happy with desktop UI, i believe it works well, but mobile UI can be improved a lot. So please do (you are talking about mobile, right?).

**Comment by viliusle** [comment]
>First thing that stands out to me is it looks like a Windows 95 application

Disagree, but I do my best to make it looks as good as possible and try to improve it when i find good ideas, but i am not designer.

>In terms of the rasterization problem, you could store vector & other tool modification data on the same layer

It would take some time to implement it, i will skip this for now and focus on more important things.

> [list]

moved to todo comment https://github.com/viliusle/miniPaint/issues/167#issuecomment-706348149

**Comment by Giwayume** [comment]
I work as a UI designer in my day job. I have ideas on how to improve it, but I don't want to go in and make sweeping changes to the look & feel if you won't accept them.

The worst part right now is with the default "dark" theme, the background and text color has too low contrast. There are many other things that can be improved, from how certain controls that are reused throughout the application look and work, to improving layouts.

![image](https://user-images.githubusercontent.com/4075314/95692724-dbf39980-0bf5-11eb-9b9c-6506cf9f58d7.png)

**Comment by viliusle** [comment]
All contrast problems should be fixed (added to todo). 

>I don't want to go in and make sweeping changes to the look & feel if you won't accept them.

Please mention all issues that you see. If it will be not hard to fix it and it will be better for most people, i will agree and implement it. Of course i would like short discussion first to avoid work, that could not be accepted for some reasons.

p.s. i had busy day, will check and test your PR tomorrow.

**Comment by Giwayume** [comment]
> Please mention all issues that you see.

I think I'm going to take the piecemeal approach and tackle sections of the app one at a time, since there's a ton of functionality in this thing. That's my intent behind #174, just starting somewhere.

If we end up replacing an existing pattern in one section of the app with a better one, maybe at that point in time consider applying that pattern across other features.

**Comment by Giwayume** [comment]
One thing specifically for mobile, most mobile browsers trick the website into thinking it has a lower resolution than it actually does, e.g. 1px on the webpage does not equal 1px on the phone screen. This causes noticable aliasing on the canvas, rendered much lower than the phone's screen resolution. Just need to take devicePixelRatio into account when rendering the canvas to fix this.

https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio
