### ISSUE TITLE
Can i easily integrate it with Angular (rather calling the deployed service using with <iframe>)? Has anyone tried out?

### ISSUE THREAD

**Issue by SirajChaudhary** [viliusle/miniPaint#169]
Can i easily integrate it with Angular (rather calling the deployed service using with <iframe>)? Has anyone tried this?

**Comment by Giwayume** [comment]
I think the short answer is no. Looks to me like the CSS is designed to style the whole page, starting with the `<body>` element. Javascript would also need to change to be able to generate the basic app markup as opposed to relying on index.html to instantiate elements.

**Comment by Giwayume** [comment]
@viliusle any reason you're keeping this open?

This issue is basically asking to be able to instantiate miniPaint on the same page as a web app (possibly open it as a full screen overlay, similar to other photo gallery libraries). The biggest problem this presents is possible CSS collisions with the page it is injected on, unless you go the Web Component/Shadow DOM route which has ok support across modern browsers. https://caniuse.com/shadowdomv1

**Comment by viliusle** [comment]
It is not possible now, and making it possible would require some work which would give no benefit to 99% user. 
So answer is really "**No**".
