### ISSUE TITLE
[Feature Request] Improve color selection

### ISSUE THREAD

**Issue by Giwayume** [viliusle/miniPaint#174]
- [x] Ability to leave color selection gradient open for more art-oriented tasks that require constant fiddling
- [x] Display RGB/HSV entry as sliders that show a preview of the change in color from 0 to 255
- [x] Color swatches / recently selected colors
- [x] Pull up color selection block instead of native HTML color picker when selecting color in the layer details (or elsewhere) for a unified experience
- [x] General look/feel improvements

I'll probably work on this next.

**Comment by Giwayume** [comment]
I'm thinking this last point "Pull up color selection block instead of native HTML color picker" is going to require a popup implementation that lets you drag it around the screen for it to be useful.

**Comment by Giwayume** [comment]
I have a few remaining ideas for the future but I think this is good for now.

**Comment by viliusle** [comment]
1.  I often miss ability to see current color in HEX. I know i can do "Toggle color channels", but leaving it open all time takes too much space. So the idea is to move HEX field to "Toggle Color Picker" are, since this area usually are opened, only because its too important to close? What do you think about it? 

2. Also clicking on small color preview on right sidebar, could open "Toggle Color Picker" area, if it is closed.

3. TODO: implement new color picker also on Menu > Tools > replace color/borders. (People like replace color, and after testing I believe that your Swatches feature could improve UX for color replace.)

**Comment by Giwayume** [comment]
1. I think it depends on the person how important that is, like web designers care a lot more about hex than artists or photo manipulators, but moving it there is probably fine.
2. ok
3. Right, I wasn't aware of those items having color pickers
