### ISSUE TITLE
[Usability] Remove the link from the miniPaint logo

### ISSUE THREAD

**Issue by Giwayume** [viliusle/miniPaint#178]
Clicking on the logo refreshes the page, which leads to potentially losing progress if you accidentally clicked on it.

I don't see the point in making the logo a link. If you wanted a new canvas, you can do `File -> New`.

**Comment by viliusle** [comment]
I understand you, but i disagree. Logo on link very close to being a standart, most people know and understand what happens if you click logo on any page (you will get to homepage or something similar).

Why it exist? For quick way to another instance of miniPaint on another tab using CTRL + click or middle mouse click.

One of solutions can be to modify this in a way, that using normal mouse click does nothing, but using CTRL + click still opens new tab.

**Comment by Giwayume** [comment]
Another solution is keep track of whether or not the user has unsaved changes & warn them before they're about to lose them.
