### ISSUE TITLE
Suggestion?: Text is attached to image layer

### ISSUE THREAD

**Issue by pillows** [viliusle/miniPaint#23]
Would it be possible to make text it's own layer? When putting text on an image, it's attached to the image's layer making it not possible to move text where you would like.

**Comment by viliusle** [comment]
You can move layer :), just create separate layer for text, but yes, you can not edit already added objects including text. This way lets you use whatever tools you want for added text, for example add blur, erase part of letter.
But i understand your problem. I will think about it in future. Because it require lots of changes in all application.

**Comment by gargsms** [comment]
@pillows Please see #24 for this. It covers this exact case. Till it is merged, feel free to use my fork.

**Comment by sajangrg** [comment]
I had the same issue as @pillows had so I edited the code in popup.js from libs folder. Well, I was able to get new layer everytime I saved the text.
Does it solve your problem with text? 

![popup-line240-252](https://cloud.githubusercontent.com/assets/16367720/17507423/4600c51a-5e2f-11e6-9f1e-8f17d79ed31a.png)

**Comment by viliusle** [comment]
i will add this functionality (auto create new layer before adding text) on next version. (soon)

**Comment by viliusle** [comment]
implemented.
