### ISSUE TITLE
Select Layer

### ISSUE THREAD

**Issue by josephsr** [viliusle/miniPaint#254]
Probably a very simple one but been struggling with my limited knowledge of Javascript. Currently, when I pick a tool and use it it puts it on a new layer. I have created some custom layers onload. I am able to set the visibility by using toggle_visibility

What I am not able to do
1) Select the layer using the id (have stored it)
2) Any paint on it (brush, pencil etc) needs to be on the above selected layer. Currently it puts it on a new layer. Trying to tinker bundle.js or brush.js/pencil.js did not help

Thanks in advance

Regards,
Joseph

**Comment by viliusle** [comment]
1. select(id) - check [wiki](https://github.com/viliusle/miniPaint/wiki/Class:-Base_layers_class)
2. it creates additional layer, if current layer is different or has different settings. Remember, pencil/brush data is basically array of positions, not raster data.
https://github.com/viliusle/miniPaint/blob/master/src/js/tools/pencil.js#L35

p.s. do not edit bundle.js, this i auto-generated file.

**Comment by josephsr** [comment]
I had tried to force and update rather than insert by editing 
		if (config.layer.type != this.name || params_hash != this.params_hash) { to
		if (1==2) {
but it still goes to a new layers rathan than updating existing layer

**Comment by Giwayume** [comment]
That's how the pencil tool is designed. If you draw a line with the pencil, change the selected color, then draw another line, that second line will be drawn on a new layer because the pencil only supports one color per layer. You can change the color of a pencil layer later in the layer details.

![image](https://user-images.githubusercontent.com/4075314/117603194-7f6f4300-b120-11eb-8271-6a7bbb40abad.png)

It doesn't work like a typical raster image editor like you may be used to. 

But honestly, the pencil tool might as well be converted to a raster tool because changing the color all at once after the fact is the only thing it has going for it. After you draw a line with the pencil, you can't immediately erase it, have to go to a menu item to rasterize it first. In other raster editors, changing the color of a raster line is simple with the use of an alpha lock button and painting over it. The vector-like nature of the pencil tool isn't very helpful because of the lack of ways to edit it after the fact.

**Comment by josephsr** [comment]
1. Also, these does not seem to work -

document.getElementById('miniPaint').contentWindow.Layers.select(id);
window.Layers.select(id);

2. Is there anyway I can merge the pencil drawing onto my custom created layer

**Comment by Giwayume** [comment]
Need to convert the pencil layer to raster, 

![image](https://user-images.githubusercontent.com/4075314/117665676-16fc8200-b171-11eb-908b-4047b3234b51.png)

Then merge down.

![image](https://user-images.githubusercontent.com/4075314/117665824-3c898b80-b171-11eb-9468-8a1ea80c3f83.png)

**Comment by viliusle** [comment]
it works, I just tested. 

```
var Layers = document.getElementById('myFrame').contentWindow.Layers;
Layers.select(1);
```

Take a look at examples: https://github.com/viliusle/miniPaint/tree/master/examples

>I think the class which has select method is not getting exported

There is only 1 class, that handles layer functions, if `toggle_visibility()` works fine, `select()` must also work.

Also check console for errors. If you get 0, means you tried to load image and select some layer. After selecting layer, image was actually loaded and probably selected. It means you have to wait till image is loaded. This could be case when `select()` does not work and returns 0 errors. In this case you have 2 options:

1. use `setTimeout` - this is bad way (zooom.html).
2. use `async` + `await` - correct way (add-edit-imgData.html).

**Comment by josephsr** [comment]
Thank you so much. For now, I will build plain interface with image editing, will keep following here and incorporate this if and when the feature gets added.
