### ISSUE TITLE
Image Rotation from its center.

### ISSUE THREAD

**Issue by sajangrg** [viliusle/miniPaint#27]
miniPaint works well. Great job.  When it comes to image rotation from menu, I'm having difficulty rotating image from its center. It works fine when the image fits well in canvas but when small sized image is imported and rotated, the image goes round the canvas instead of rotating from its center. If you could help with this, it would be much more easier for us. Thank you!

**Comment by viliusle** [comment]
Now, after rotation, use layer > trim to move rotated image to top-left corner.
I see your problem, i will add option to rotate only visible part from its center, not from all area center.

**Comment by sajangrg** [comment]
I actually need this rotation of image from its center rather than from its
canvas. Similar to as it is in the link: http://jsfiddle.net/fabricjs/6ydPq/
.I have to rename those layer on double click as well.
I would support you making some payment for these feature. You just need to
make this happen and send it to me.
Hoping for you response.
Thank you!

**Comment by viliusle** [comment]
It is nice example, very user friendly (selecting objects, not area). I can not implement all these features now, because half of other functions will stop working (for example effects). I am going to ... but it will take time and it should be next major update. 

For now i will add layer rename and improve rotation, will try in next few days.

**Comment by sajangrg** [comment]
Alright, thank you!

**Comment by viliusle** [comment]
Rotation from center added. (menu->image->rotate->area->visible)
