### ISSUE TITLE
Savedimage size

### ISSUE THREAD

**Issue by lookingdown** [viliusle/miniPaint#278]
Hi...
When opening and saving an image (jpeg) which works well by the way..
The save image is a lot smaller than the original..
If I open a photo 7.3Mb,  4608 × 3456px
When I save it it is the same size 4608 × 3456px but lower quality at 2.4Mb..
This seems to have something to do with canvas size on page when I open photo in editor an a smaller browser window It results in an even smaller file..
Is this expected behavior ? 
Is there a way to open an image and save the image with full pixel resolution resulting same as original (i.e. open an image apply filter and save same photo 7.3Mb,  4608 × 3456px ).? :)
Thanks a lot

**Comment by viliusle** [comment]
>Is there a way to open an image and save the image with full pixel resolution resulting same as original

This is default behaviour, unless you resize image before saving. When you open image, it is not resized,  you just see it smaller if it does not fit screen. 

**I guess you opened JPG file that was saved at very high quality (usually mistake and should never be done).**

In general, image size depends on:

- image dimensions
- image last saved quality
- image itself (amount of colors, edges)
- saving format
- saving quality.
- For JPG - how many times image was already saved in this format, because each time you do it, you loose lots of quality, and after infinity saves you would probably end up just noise and very small image size.

**TIp:** Try Never edit JPG file, if you know that you will need to edit it again - save copy of PNG for future edits. Every time you save image as JPG, you lose quality.

**Comment by lookingdown** [comment]
Ok.. understand (I think) the images as from a digital camera a good one and not edited..
I will do some pre and post processing before opening in the editor convert to PNG and save as PNG and convert after save to jpeg again. I AM using a photo organizing app photoprism and they are all jpg from câmera..  added a link for the photos to be securely opened in minipaint, if need to be edited and need to be save back with same format.  Perhaps this workaround to png and back will help the kvm vps I use is quite powerful 8gb RAM só I do not think it will make much difference in the user experiente apartamento from png will be much bigger in Mb..  I will setit up later today or tomorrow..  
Thanks again..
