### ISSUE TITLE
Your App has been stolen

### ISSUE THREAD

**Issue by anonimo82** [viliusle/miniPaint#289]
Look here:
https://play.google.com/store/apps/details?id=com.ulm.photoeditorplus

**Comment by Giwayume** [comment]
Minipaint is an MIT licensed project, it explicitly states in the license text you have the right to sell copies so long as the copyright notice is left in the codebase.

Similar thing for Sonic Colors: Ultimate on the Nintendo 3DS, that team used parts of the MIT licensed Godot engine and didn't credit the engine in-game. They're not required to by the license, so long as the original license text exists in the codebase. Fans of the Godot engine got mad at the developers of that game due to this, but they weren't technically in the wrong, just arguably morally.

Also I doubt they're making much money on that. Minipaint has had a lot of improvements to work on mobile screens recently, but it definitely wouldn't be my mobile photo editor of choice if I'm going to spend money on a mobile app lol.

**Comment by Giwayume** [comment]
None of the brush tools draw on existing layers, so being able to edit the alpha channel as a black/white image in order to create a custom alpha mask wouldn't be very useful if you can't draw on it directly.

**Comment by anonimo82** [comment]
Ok, but how can I outline, then?

**Comment by viliusle** [comment]
Thank you for report, but as Giwayume said, it is allowed by MIT license.

p.s. it is better to create separate ticket for another problem, because it is very hard to manage these issues with lots of questions. And your issue with alpha was not very clear to me so I can not comment.
