### ISSUE TITLE
Dynamic theme switch

### ISSUE THREAD

**Issue by anonimo82** [viliusle/miniPaint#333]
Please, add the option to dynamically change theme (light/dark) based on system setting. (Most commonly used on Android/iOS)
Thanks a lot if you do.

**Comment by viliusle** [comment]
This will look strange. I added commit, **but feature is disabled**. It may benefit for other developers.

Even we have light and dark themes, dark is default theme, which is supported well. For this reason it is default theme and I do not want to enable theme detection based on OS settings, because majority users would get light theme.

If anybody disagrees, discussion is welcome.

**Status: rejected.**
