### ISSUE TITLE
Can it support images of size in 4-5 GBs?

### ISSUE THREAD

**Issue by pdgupta84** [viliusle/miniPaint#335]
Can I upload & edit a large image of size varying in GBs? Also will I be able to zoom in & zoom out to that image to the pixel level?

**Comment by viliusle** [comment]
- There are total memory limit  on browser tab (16G limit per tab in Chrome, but 32GB on Firefox ?).
- There image dimensions limits, that browser can handle.
- Even PhotoShop has limits: "PSD limits pixel dimensions to 30,000 x 30,000 and max size to 2GB (but not PSB format, which can handle 300,000 x 300,000 and 4 exabytes).

miniPaint does not check any limits, but undo feature will not work if you load too much data. I tested minipaint with 150 MB JPG image, it works, but slowly.

I am almost sure that if you load few GB image, it will crash because of exceeding limits or will take lots of time to load on computer with lots of memory. You can always try and let us know. But I personally would try to use desktop apps to edit such big images.

**Comment by viliusle** [comment]
And it is nothing can be done to optimize even more, because miniPaint is already optimized to save memory as much as possible.

**Comment by pdgupta84** [comment]
Thanks for the inputs.

**Comment by pdgupta84** [comment]
Hi,
Today I tried opening a 40 MB photo on minipaint. But it gave me error. You had mentioned that you were able to open a 150 MB photo (though it was slow). So I was curious to know how you managed to open the same? Any setting that we need to take care of? Please let me know. Thanks.

**Comment by viliusle** [comment]
Can you share that image? 
I image if it is few colors PNG with very big dimensions, miniPaint could have problems. OR maybe wrong format? it should open 40 MB images without big issues.

**Comment by pdgupta84** [comment]
You can try this file: https://effigis.com/wp-content/themes/effigis_2014/img/GeoEye_GeoEye1_50cm_8bit_RGB_DRA_Mining_2009FEB14_8bits_sub_r_15.jpg 
It does not works both ways, either by specifying URL or by downloading & specifying its local path.

**Comment by viliusle** [comment]
![11](https://user-images.githubusercontent.com/3708786/191857654-507fab0a-e0de-4103-ade2-7de6fd77b243.jpg)
I can open and edit it. 

>But it gave me error
What errors? how you are opening it?

**Comment by pdgupta84** [comment]
Here is the screenshot of error. 
![error](https://user-images.githubusercontent.com/13734707/191862978-d0b4e64d-e4e1-461b-9cf5-43c001c7819f.png)
I'm using option File -> Open -> Open URL & giving the URL https://effigis.com/wp-content/themes/effigis_2014/img/GeoEye_GeoEye1_50cm_8bit_RGB_DRA_Mining_2009FEB14_8bits_sub_r_15.jpg in there.

**Comment by viliusle** [comment]
You get CORS (https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) error, basically host does not allow to take resources from that domain using JavaScript. 
You should save that image on your computer and open it locally.
