### ISSUE TITLE
Why can I not resize an image after rotating it ?I want to resize it by dragging the corners.

### ISSUE THREAD

**Issue by sidgore** [viliusle/miniPaint#96]

**Comment by sidgore** [comment]
Where to change enable_controls=true for a rotated image?

**Comment by viliusle** [comment]
Sorry, not possible yet, only in future. But you can still resize using "layer details" on right sidebar.

**Comment by sidgore** [comment]
If I want to add that functionality where should I begin?

**Comment by viliusle** [comment]
Look at src/js/core/base-selection.js , comment out line 241, and system will allow resize actions on rotated object.

But rotated object has different position, and because system can not detect when you hover mouse over rotated object, you will not be able to resize image.

matching is done on live 299. Fix would be fix this matching when object is rotated and probably recalculate how many pixels mouse was dragged.
